<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Tu perfil de aprendizaje en Lexi.">
  <meta name="robots" content="noindex">
  <title>Lexi | Perfil</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="style.css">
</head>
<body data-server-profile="true">
<a href="#mainContent" class="skip-link">Saltar al contenido</a>
<header class="header"><div class="header-left"><div class="logo"><img src="icons/logo.svg" alt="Logo Lexi"></div><button class="nav-toggle" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="mainNav"><i class="bi bi-list"></i></button><nav class="nav-left" id="mainNav"><a href="app.html">Inicio</a><a href="biblioteca.html">Biblioteca</a><a href="ejercicios.html">Ejercicios</a></nav></div><div class="header-right"><button class="icon-btn" type="button" aria-label="Tu progreso" data-progress-trigger><i class="bi bi-rocket-takeoff" style="font-size:1.45rem;"></i></button><div class="lang-dropdown-wrap" data-lang-wrap><button class="icon-btn" type="button" aria-label="Seleccionar idioma" data-lang-trigger aria-haspopup="true" aria-expanded="false"><img src="" alt="Idioma seleccionado" id="activeLangFlag"></button><div class="lang-dropdown" id="langDropdown" hidden></div></div><script>(function(){var f={en:"icons/flags/united_kingdom_flag.svg",fr:"icons/flags/france_flag.svg",de:"icons/flags/germany_flag.svg",es:"icons/flags/spain_flag.svg",it:"icons/flags/italy_flag.svg",pt:"icons/flags/brazil_flag.svg",no:"icons/flags/norway_flag.svg",sv:"icons/flags/sweden_flag.svg",dk:"icons/flags/denmark_flag.svg",fi:"icons/flags/finland_flag.svg",ko:"icons/flags/south_korea_flag.svg",ja:"icons/flags/japan_flag.svg",zh:"icons/flags/china_flag.svg",ru:"icons/flags/russia_flag.svg",ua:"icons/flags/ukraine_flag.svg",bg:"icons/flags/bulgaria_flag.svg",ro:"icons/flags/romania_flag.svg",cs:"icons/flags/czech_republic_flag.svg",sk:"icons/flags/slovakia_flag.svg",hu:"icons/flags/hungary_flag.svg",gr:"icons/flags/greece_flag.svg",ar:"icons/flags/saudi_arabia_flag.svg",vi:"icons/flags/vietnam_flag.svg",pl:"icons/flags/poland_flag.svg",tr:"icons/flags/turkey_flag.svg",id:"icons/flags/indonesia_flag.svg",he:"icons/flags/israel_flag.svg",hi:"icons/flags/india_flag.svg",th:"icons/flags/thailand_flag.svg",nl:"icons/flags/netherlands_flag.svg"};var img=document.getElementById("activeLangFlag");if(img)img.src=f[localStorage.getItem("lexiLang")||"en"]||f.en;})();</script><a href="perfil.html" class="icon-btn" aria-label="Perfil"><img src="icons/profile.svg" alt="Perfil"></a><button class="icon-btn utility-trigger" type="button" data-utility-trigger aria-label="Abrir menu secundario" aria-expanded="false"><img src="icons/menu.svg" alt="" aria-hidden="true"></button></div></header>
<main id="mainContent" class="profile-main">
  <div class="profile-hero"><div class="profile-avatar" id="profileAvatar">{{ strtoupper(mb_substr($user->name, 0, 1)) }}</div><div class="profile-hero-info"><div class="profile-name-wrap"><h1 class="profile-name" id="profileName">{{ $user->name }}</h1><button class="profile-edit-btn" id="btnEditName" aria-label="Editar nombre"><i class="bi bi-pencil"></i></button></div><p class="profile-since" id="profileSince">Miembro desde {{ optional($user->created_at)->translatedFormat('F Y') }}</p><a href="progreso.html" class="profile-progress-link"><i class="bi bi-bar-chart-fill"></i> Ver tu progreso →</a></div></div>
  <section class="profile-section"><h2 class="profile-section-title">Información de cuenta</h2><div class="profile-settings-card">@if (session('status'))<div class="alert alert-success mb-3">{{ session('status') }}</div>@endif @if ($errors->any())<div class="alert alert-danger mb-3">{{ $errors->first() }}</div>@endif <form method="POST" action="{{ route('profile.update') }}">@csrf<div class="profile-setting-row"><span class="profile-setting-label">Nombre de usuario</span><div class="profile-setting-control"><span class="profile-setting-value" id="displayName">{{ $user->name }}</span><button class="btn btn-outline-secondary btn-sm" type="button" id="btnEditName2">Editar</button></div></div><div class="profile-setting-row" id="editNameRow" hidden><label class="profile-setting-label" for="inputName">Nuevo nombre</label><div class="profile-setting-control"><input class="profile-input" type="text" id="inputName" name="name" maxlength="30" value="{{ old('name', $user->name) }}" placeholder="Tu nombre"><button class="btn btn-primary btn-sm" id="btnSaveName" type="submit">Guardar</button><button class="btn btn-outline-secondary btn-sm" id="btnCancelName" type="button">Cancelar</button></div></div><div class="profile-setting-row"><span class="profile-setting-label">Correo electrónico</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $user->email }}</span><span class="profile-verified-badge"><i class="bi bi-patch-check-fill"></i> {{ $user->email_verified_at ? 'Verificado' : 'Pendiente' }}</span></div></div><div class="profile-setting-row"><span class="profile-setting-label">Idioma nativo</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $languages[$user->mother_tongue_code] ?? strtoupper((string) $user->mother_tongue_code) }}</span><span class="profile-setting-hint">Se fija al crear la cuenta y no se puede modificar.</span></div></div></form><div class="profile-setting-row" style="flex-direction:column;align-items:stretch;gap:0.75rem"><span class="profile-setting-label">Idiomas estudiados</span><div id="langChips" class="profile-studied-list">@forelse ($user->userLanguages as $userLanguage)<div class="profile-studied-row{{ $userLanguage->is_active ? ' is-active' : '' }}"><div class="profile-studied-left"><span>{{ $languages[$userLanguage->language_code] ?? strtoupper($userLanguage->language_code) }}</span></div>@if ($userLanguage->is_active)<span class="profile-studied-badge"><i class="bi bi-check-circle-fill"></i> activo</span>@endif</div>@empty<span class="profile-setting-hint" style="font-style:italic">Aún no has configurado idiomas de estudio.</span>@endforelse</div></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title">Sesión</h2><div class="profile-settings-card"><div class="profile-setting-row"><span class="profile-setting-label">Sesión activa</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-outline-secondary btn-sm" type="submit">Cerrar sesión</button></form></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title" style="color:#dc3545">Zona de riesgo</h2><div class="profile-settings-card profile-danger-card"><div class="profile-setting-row profile-setting-danger"><div><span class="profile-setting-label">Eliminar cuenta</span><p class="profile-setting-hint">Borra tu cuenta y todos tus datos permanentemente.</p></div><form method="POST" action="{{ route('profile.destroy') }}" onsubmit="return confirm('Esta acción eliminará tu cuenta. ¿Continuar?');">@csrf @method('DELETE')<button class="btn btn-danger btn-sm" type="submit">Eliminar cuenta</button></form></div></div></section>
</main>
<footer class="footer"><div class="footer-inner"><div class="footer-brand"><a href="app.html" class="footer-logo" aria-label="Inicio">Lexi</a><p class="footer-tagline">Vocabulario personalizado, ejercicios prácticos y seguimiento claro de tu progreso.</p></div><nav class="footer-nav" aria-label="Plataforma"><h3 class="footer-heading">Plataforma</h3><ul><li><a href="app.html">Inicio</a></li><li><a href="biblioteca.html">Biblioteca</a></li><li><a href="ejercicios.html">Ejercicios</a></li><li><a href="progreso.html">Progreso</a></li></ul></nav><nav class="footer-nav" aria-label="Cuenta"><h3 class="footer-heading">Cuenta</h3><ul><li><a href="perfil.html">Perfil</a></li><li><a href="producto.html">Premium</a></li><li><a href="carrito.html">Carrito</a></li></ul></nav><nav class="footer-nav" aria-label="Soporte"><h3 class="footer-heading">Soporte</h3><ul><li><a href="contacto.html">Contacto</a></li><li><a href="info.html">Información</a></li><li><a href="terminos.html">Términos</a></li><li><a href="privacidad.html">Privacidad</a></li></ul></nav><div class="footer-stats" aria-label="Resumen del prototipo"><div class="footer-stat"><span class="footer-stat-num">30</span><span class="footer-stat-label">idiomas<br>disponibles</span></div><div class="footer-stat"><span class="footer-stat-num">2</span><span class="footer-stat-label">idiomas<br>funcionales</span></div></div></div><div class="footer-bottom"><p>&copy; 2026 Lexi. Todos los derechos reservados.</p></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="js/script.js"></script><script> (function(){const showEdit=(show)=>{document.getElementById('editNameRow').hidden=!show;document.querySelectorAll('[id="btnEditName"],[id="btnEditName2"]').forEach(b=>b.hidden=show);if(show){document.getElementById('inputName').focus();}}; document.getElementById('btnEditName').addEventListener('click',()=>showEdit(true));document.getElementById('btnEditName2').addEventListener('click',()=>showEdit(true));document.getElementById('btnCancelName').addEventListener('click',()=>showEdit(false));})(); </script>
</body>
</html>