@extends('layouts.site', ['title' => 'Lexi | Perfil', 'description' => 'Tu perfil de aprendizaje en Lexi.', 'robots' => 'noindex', 'bodyAttributes' => 'data-server-profile="true"'])

@section('content')
<main id="mainContent" class="profile-main">
  <div class="profile-hero"><div class="profile-avatar" id="profileAvatar">{{ strtoupper(mb_substr($user->name, 0, 1)) }}</div><div class="profile-hero-info"><div class="profile-name-wrap"><h1 class="profile-name" id="profileName">{{ $user->name }}</h1><button class="profile-edit-btn" id="btnEditName" aria-label="Editar nombre"><i class="bi bi-pencil"></i></button></div><p class="profile-since" id="profileSince">Miembro desde {{ optional($user->created_at)->translatedFormat('F Y') }}</p><a href="progreso.html" class="profile-progress-link"><i class="bi bi-bar-chart-fill"></i> Ver tu progreso →</a></div></div>
  <section class="profile-section"><h2 class="profile-section-title">Información de cuenta</h2><div class="profile-settings-card">@if (session('status'))<div class="alert alert-success mb-3">{{ session('status') }}</div>@endif @if ($errors->any())<div class="alert alert-danger mb-3">{{ $errors->first() }}</div>@endif <form method="POST" action="{{ route('profile.update') }}">@csrf<div class="profile-setting-row"><span class="profile-setting-label">Nombre de usuario</span><div class="profile-setting-control"><span class="profile-setting-value" id="displayName">{{ $user->name }}</span><button class="btn btn-outline-secondary btn-sm" type="button" id="btnEditName2">Editar</button></div></div><div class="profile-setting-row" id="editNameRow" hidden><label class="profile-setting-label" for="inputName">Nuevo nombre</label><div class="profile-setting-control"><input class="profile-input" type="text" id="inputName" name="name" maxlength="30" value="{{ old('name', $user->name) }}" placeholder="Tu nombre"><button class="btn btn-primary btn-sm" id="btnSaveName" type="submit">Guardar</button><button class="btn btn-outline-secondary btn-sm" id="btnCancelName" type="button">Cancelar</button></div></div><div class="profile-setting-row"><span class="profile-setting-label">Correo electrónico</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $user->email }}</span><span class="profile-verified-badge"><i class="bi bi-patch-check-fill"></i> {{ $user->email_verified_at ? 'Verificado' : 'Pendiente' }}</span></div></div><div class="profile-setting-row"><span class="profile-setting-label">Idioma nativo</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $languages[$user->mother_tongue_code] ?? strtoupper((string) $user->mother_tongue_code) }}</span><span class="profile-setting-hint">Se fija al crear la cuenta y no se puede modificar.</span></div></div></form><div class="profile-setting-row" style="flex-direction:column;align-items:stretch;gap:0.75rem"><span class="profile-setting-label">Idiomas estudiados</span><div id="langChips" class="profile-studied-list">@forelse ($user->userLanguages as $userLanguage)<div class="profile-studied-row{{ $userLanguage->is_active ? ' is-active' : '' }}"><div class="profile-studied-left"><span>{{ $languages[$userLanguage->language_code] ?? strtoupper($userLanguage->language_code) }}</span></div>@if ($userLanguage->is_active)<span class="profile-studied-badge"><i class="bi bi-check-circle-fill"></i> activo</span>@endif</div>@empty<span class="profile-setting-hint" style="font-style:italic">Aún no has configurado idiomas de estudio.</span>@endforelse</div></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title">Sesión</h2><div class="profile-settings-card"><div class="profile-setting-row"><span class="profile-setting-label">Sesión activa</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-outline-secondary btn-sm" type="submit">Cerrar sesión</button></form></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title" style="color:#dc3545">Zona de riesgo</h2><div class="profile-settings-card profile-danger-card"><div class="profile-setting-row profile-setting-danger"><div><span class="profile-setting-label">Eliminar cuenta</span><p class="profile-setting-hint">Borra tu cuenta y todos tus datos permanentemente.</p></div><form method="POST" action="{{ route('profile.destroy') }}" onsubmit="return confirm('Esta acción eliminará tu cuenta. ¿Continuar?');">@csrf @method('DELETE')<button class="btn btn-danger btn-sm" type="submit">Eliminar cuenta</button></form></div></div></section>
</main>
@endsection

@section('inlineScripts')
<script> (function(){const showEdit=(show)=>{document.getElementById('editNameRow').hidden=!show;document.querySelectorAll('[id="btnEditName"],[id="btnEditName2"]').forEach(b=>b.hidden=show);if(show){document.getElementById('inputName').focus();}}; document.getElementById('btnEditName').addEventListener('click',()=>showEdit(true));document.getElementById('btnEditName2').addEventListener('click',()=>showEdit(true));document.getElementById('btnCancelName').addEventListener('click',()=>showEdit(false));})(); </script>
@endsection