@extends('layouts.admin', ['title' => 'Lexi | Admin Users', 'description' => 'Gestión de usuarios en Lexi Admin.', 'sidebarNoteTitle' => 'Users', 'sidebarNoteText' => 'Gestión de cuentas, perfiles y estados de acceso.'])

@section('content')
<section class="admin-page-head">
	<div>
		<h1>Users</h1>
		<p>Vista real de usuarios, roles y lengua nativa desde la base de datos.</p>
	</div>
	<div class="admin-page-actions">
		<a class="admin-btn admin-btn--ghost" href="admin.html"><i class="bi bi-arrow-left"></i> Panel</a>
	</div>
</section>
<section class="admin-stats">
	<article class="admin-card admin-stat"><div class="admin-stat__row"><span class="admin-chip admin-chip--violet">Users</span><div class="admin-stat__icon"><i class="bi bi-people"></i></div></div><p class="admin-stat__value">{{ number_format($stats['users']) }}</p><p class="admin-stat__label">Cuentas registradas</p><span class="admin-stat__meta"><i class="bi bi-database"></i> Tabla real de users</span></article>
	<article class="admin-card admin-stat"><div class="admin-stat__row"><span class="admin-chip admin-chip--green">Activos</span><div class="admin-stat__icon"><i class="bi bi-check2-circle"></i></div></div><p class="admin-stat__value">{{ number_format($stats['active']) }}</p><p class="admin-stat__label">Usuarios verificados</p><span class="admin-stat__meta"><i class="bi bi-lightning-charge"></i> Email verificado</span></article>
	<article class="admin-card admin-stat"><div class="admin-stat__row"><span class="admin-chip admin-chip--amber">Pendientes</span><div class="admin-stat__icon"><i class="bi bi-hourglass-split"></i></div></div><p class="admin-stat__value">{{ number_format($stats['pending']) }}</p><p class="admin-stat__label">Verificación pendiente</p><span class="admin-stat__meta"><i class="bi bi-envelope"></i> Requiere revisión</span></article>
	<article class="admin-card admin-stat"><div class="admin-stat__row"><span class="admin-chip admin-chip--violet">Teachers</span><div class="admin-stat__icon"><i class="bi bi-mortarboard"></i></div></div><p class="admin-stat__value">{{ number_format($stats['teachers']) }}</p><p class="admin-stat__label">Teacher accounts</p><span class="admin-stat__meta"><i class="bi bi-person-workspace"></i> Rol teacher</span></article>
</section>
<section class="admin-card"><div class="admin-card__inner"><div class="admin-card__head"><div><h2>User directory</h2><p>Vista general de usuarios administrables.</p></div></div><form class="row g-3 mb-4" method="get" action="{{ route('admin-users') }}"><div class="col-md-10"><label class="form-label" for="userSearch">Buscar usuario</label><input class="form-control" id="userSearch" type="search" name="q" value="{{ $filters['q'] }}" placeholder="nombre, apellido o email"></div><div class="col-md-2 d-flex align-items-end"><button class="admin-btn admin-btn--primary w-100" type="submit"><i class="bi bi-search"></i> Filtrar</button></div></form><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Native</th><th>Learning</th><th>Status</th></tr></thead><tbody>@forelse($users as $user) @php($fullName = trim(($user->name ?? '') . ' ' . ($user->surname ?? ''))) @php($roles = $user->roles->pluck('name')->map(fn ($role) => ucfirst($role))->join(', ')) @php($learning = $user->userLanguages->pluck('language_code')->map(fn ($code) => $languageLabels[$code] ?? strtoupper($code))->join(', ')) <tr><td>{{ $fullName ?: 'Sin nombre' }}</td><td>{{ $user->email }}</td><td>{{ $roles ?: 'Sin rol' }}</td><td>{{ $languageLabels[$user->mother_tongue_code] ?? strtoupper((string) $user->mother_tongue_code) ?: 'N/D' }}</td><td>{{ $learning ?: 'Sin idiomas' }}</td><td><span class="admin-status {{ $user->email_verified_at ? 'admin-status--active' : 'admin-status--review' }}">{{ $user->email_verified_at ? 'Activo' : 'Pendiente' }}</span></td></tr> @empty <tr><td colspan="6">No hay usuarios para ese filtro.</td></tr> @endforelse</tbody></table></div>@if ($users->hasPages()) <div class="d-flex justify-content-between align-items-center pt-3"><p class="mb-0 text-muted small">Mostrando {{ $users->firstItem() }}-{{ $users->lastItem() }} de {{ $users->total() }} filas.</p><div>{{ $users->onEachSide(1)->links() }}</div></div>@endif</div></section>
@endsection